### ISSUE TITLE
DIC seems to be limited to dumping CDs at 200 sectors a second on Windows 11 ARM

### ISSUE THREAD

**Issue by larsenv** [saramibreak/DiscImageCreator#116]
**Version**
I've tested with version 20220301.

**Describe the bug**
Previously, I've been dumping CD-ROMs with my Plextor PX-W5224TA in an enclosure, connected to an Intel Mac running Windows 7 on Parallels Desktop. This setup has worked well, and I've been able to get proper dumps (which match other people's dumps).

I've upgraded to an M1 Pro MacBook Pro that's using the ARM architecture. I'm now running Windows 11 ARM with Parallels Desktop (and I can only run VMs with the ARM architecture). Dumps still happen properly, however no matter what setting I use, the dump speed seems to be limited to 200 sectors a second approximately, which seems to be slower than what I had before. If I change the drive speed, it still dumps at the same speed.

DVDs seem to dump at a reasonable speed. This problem is also happening on my Plextor Premium external, my ASUS BW-16D1HT (with an enclosure), and my Plextor PX-760A (with an enclosure).

By the way, Parallels Desktop has an option to connect a drive as a DVD drive, but DIC seems to fail immediately when I use it. I connect the drives via the USB passthrough options on the VM.

**Screenshots**
```DiscImageCreator.exe cd E "ISO\GameName\GameName.bin" 72 /c2 20 /ns /sf```

I'm using DIC with MPF.

**Disc title**
N/A, this problem happens with all CD-ROMs.

**Disc ringcode**
N/A

**URL**
N/A

**Log file**
[NickJrPlayMath_logs.zip](https://github.com/saramibreak/DiscImageCreator/files/8171175/NickJrPlayMath_logs.zip)

**Comment by larsenv** [comment]
I can't run it.

```System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at MPF.Modules.BaseParameters.ExecuteInternalProgram(Boolean separateWindow) in B:\Programs\GitHub\MPF\MPF.Modules\BaseParameters.cs:line 271
   at MPF.Library.DumpEnvironment.<Run>b__39_0() in B:\Programs\GitHub\MPF\MPF.Library\DumpEnvironment.cs:line 273
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MPF.Library.DumpEnvironment.<Run>d__39.MoveNext() in B:\Programs\GitHub\MPF\MPF.Library\DumpEnvironment.cs:line 273
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MPF.GUI.ViewModels.MainViewModel.<StartDumping>d__58.MoveNext() in B:\Programs\GitHub\MPF\MPF\ViewModels\MainViewModel.cs:line 1285
```

**Comment by saramibreak** [comment]
Can you run it without MPF?

**Comment by larsenv** [comment]
This is a late response, but I can't. The problem is that it says it isn't compatible with the version of Windows I'm running (probably an architecture issue).
